//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountsPayableTestProdEntities : DbContext
    {
        public AccountsPayableTestProdEntities()
            : base("name=AccountsPayableTestProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_ALIAS> TB_ALIAS { get; set; }
        public virtual DbSet<TB_APPROVER> TB_APPROVER { get; set; }
        public virtual DbSet<TB_EMAIL_BACKUP> TB_EMAIL_BACKUP { get; set; }
        public virtual DbSet<TB_HIGHLIGHTS> TB_HIGHLIGHTS { get; set; }
        public virtual DbSet<TB_HISTORIC_REMIT> TB_HISTORIC_REMIT { get; set; }
        public virtual DbSet<TB_LOG_IN> TB_LOG_IN { get; set; }
        public virtual DbSet<TB_LOGIN_ROLES> TB_LOGIN_ROLES { get; set; }
        public virtual DbSet<TB_ORACLE_LEGAL_ENTITIES> TB_ORACLE_LEGAL_ENTITIES { get; set; }
        public virtual DbSet<TB_ORACLE_ORGANIZATION_TYPE> TB_ORACLE_ORGANIZATION_TYPE { get; set; }
        public virtual DbSet<TB_ORACLE_PAY_TERMS> TB_ORACLE_PAY_TERMS { get; set; }
        public virtual DbSet<TB_ORACLE_SOURCE> TB_ORACLE_SOURCE { get; set; }
        public virtual DbSet<TB_ORACLE_TYPE> TB_ORACLE_TYPE { get; set; }
        public virtual DbSet<TB_TEMPLATE> TB_TEMPLATE { get; set; }
        public virtual DbSet<TB_VIEW_PERMISSIONS> TB_VIEW_PERMISSIONS { get; set; }
        public virtual DbSet<TB_WORKSPACE> TB_WORKSPACE { get; set; }
        public virtual DbSet<WS_COMMENTS> WS_COMMENTS { get; set; }
        public virtual DbSet<WS_LAST_ACTIONS> WS_LAST_ACTIONS { get; set; }
    }
}
