//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAIL_BACKUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EMAIL_BACKUP()
        {
            this.TB_TEMPLATE = new HashSet<TB_TEMPLATE>();
        }
    
        public int EMAIL_BACKUP_ID { get; set; }
        public System.DateTime EMAIL_BACKUP_DATE { get; set; }
        public string EMAIL_BACKUP { get; set; }
        public Nullable<int> EMAIL_BACKUP_ISDISABLED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TEMPLATE> TB_TEMPLATE { get; set; }
    }
}
