//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class TB_HISTORIC_REMIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_HISTORIC_REMIT()
        {
            this.TB_TEMPLATE1 = new HashSet<TB_TEMPLATE>();
            this.TB_WORKSPACE = new HashSet<TB_WORKSPACE>();
        }
    
        public int HISTORIC_REMIT_ID { get; set; }
        public Nullable<int> FK_TB_TEMPLATE_ID { get; set; }
        public System.DateTime HISTORIC_REMIT_DATE { get; set; }
        [AllowHtml]
        public string HISTORIC_REMIT_INFO { get; set; }
    
        public virtual TB_TEMPLATE TB_TEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TEMPLATE> TB_TEMPLATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WORKSPACE> TB_WORKSPACE { get; set; }
    }
}
