//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HIGLIGHTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_HIGLIGHTS()
        {
            this.TB_TEMPLATE = new HashSet<TB_TEMPLATE>();
        }
    
        public int HIGLIGHTS_ID { get; set; }
        public System.DateTime HIGHLIGTS_DATE { get; set; }
        public string HIGLIGTHS { get; set; }
        public string HIGLIGTHS_COMMENTS { get; set; }
        public string HIGLIGTHS_INSTRUCTIONS { get; set; }
        public string HIGLIGTHS_EXCEPTIONS { get; set; }
        public string HIGLIGTHS_COMMON_ISSUES { get; set; }
        public string HIGLIGTHS_SUPPLIER_AGENCY { get; set; }
        public string HIGLIGTHS_TEMPLATE_COMMENTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TEMPLATE> TB_TEMPLATE { get; set; }
    }
}
