//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOG_IN
    {
        public int LOG_IN_ID { get; set; }
        public int FK_TB_LOGIN_ROLES_ID { get; set; }
        public string LOG_IN_PASSWORD { get; set; }
        public string LOG_IN_FULL_NAME { get; set; }
        public string LOG_IN_USER_NAME { get; set; }
        public int LOG_IN_ISDISABLED { get; set; }
    
        public virtual TB_LOGIN_ROLES TB_LOGIN_ROLES { get; set; }
    }
}
