//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOGIN_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_LOGIN_ROLES()
        {
            this.TB_LOG_IN = new HashSet<TB_LOG_IN>();
            this.TB_VIEW_PERMISSIONS = new HashSet<TB_VIEW_PERMISSIONS>();
        }
    
        public int LOGIN_ROLE_ID { get; set; }
        public string LOGIN_ROLE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LOG_IN> TB_LOG_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VIEW_PERMISSIONS> TB_VIEW_PERMISSIONS { get; set; }
    }
}
