//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORACLE_ORGANIZATION_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ORACLE_ORGANIZATION_TYPE()
        {
            this.TB_WORKSPACE = new HashSet<TB_WORKSPACE>();
            this.TB_TEMPLATE = new HashSet<TB_TEMPLATE>();
        }
    
        public int ORGANIZATION_TYPE_ID { get; set; }
        public string ORGANIZATION_TYPE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WORKSPACE> TB_WORKSPACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TEMPLATE> TB_TEMPLATE { get; set; }
    }
}
