//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEMPLATE_HISTORIC_REMIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TEMPLATE_HISTORIC_REMIT()
        {
            this.TB_TEMPLATE = new HashSet<TB_TEMPLATE>();
        }
    
        public int TEMPLATE_HISTORIC_REMIT_ID { get; set; }
        public int FK_TB_TEMP_ID { get; set; }
        public int FK_TB_HISTORIC_REMIT_ID { get; set; }
    
        public virtual TB_HISTORIC_REMIT TB_HISTORIC_REMIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TEMPLATE> TB_TEMPLATE { get; set; }
    }
}
