//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEMPLATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TEMPLATE()
        {
            this.TB_HIGHLIGHTS = new HashSet<TB_HIGHLIGHTS>();
            this.TB_HISTORIC_REMIT = new HashSet<TB_HISTORIC_REMIT>();
            this.TB_ALIAS = new HashSet<TB_ALIAS>();
            this.TB_EMAIL_BACKUP = new HashSet<TB_EMAIL_BACKUP>();
        }
    
        public int TEMP_ID { get; set; }
        public string TEMP_TAX_ID { get; set; }
        public string TEMP_REMIT_TO { get; set; }
        public string TEMP_SUPPLIER_NAME { get; set; }
        public string TEMP_SUPPLIER_NUMBER { get; set; }
        public Nullable<int> FK_TB_TEMPLATE_HISTORIC_REMIT_ID { get; set; }
        public string TEMP_VENDOR_ACCOUNT { get; set; }
        public Nullable<int> FK_TB_TEMPLATE_ALIAS_ID { get; set; }
        public string TEMP_SUPPLIER_SITE { get; set; }
        public Nullable<int> FK_TB_LEGAL_ENTITY_ID { get; set; }
        public string TEMP_TAXPAYER_ID { get; set; }
        public Nullable<int> FK_TB_ORACLE_TYPE_ID { get; set; }
        public string TEMP_ORACLE_DESCRIPTION { get; set; }
        public Nullable<int> FK_TB_ORACLE_PAY_TERMS_ID { get; set; }
        public string TEMP_DISTRIBUTION_SET { get; set; }
        public Nullable<int> FK_TB_ORACLE_SOURCE_ID { get; set; }
        public string TEMP_ORACLE_NOTES { get; set; }
        public string TEMP_ORACLE_INSTRUCTIONS { get; set; }
        public Nullable<int> FK_TB_HIGHLIGHTS_ID { get; set; }
        public Nullable<int> FK_TB_EMAIL_BACKUP_ID { get; set; }
        public Nullable<int> FK_TB_APPROVER_ID { get; set; }
        public string TEMP_APPROVER_COMMENTS { get; set; }
        public string TEMP_INVOICE_FORMAT { get; set; }
        public string TEMP_INVOICE_TYPE { get; set; }
        public int TEMP_ISDISABLED { get; set; }
        public string TEMP_FOLDER { get; set; }
        public string TEMP_PAYMENT_METHOD { get; set; }
        public string TEMP_REMIT_TOACCOUNT { get; set; }
        public string TEMP_BILLING_PERIOD { get; set; }
        public string TEMP_DISTRIBUTION_COMBINATION { get; set; }
        public string TEMP_ACCOUNTING_DATE { get; set; }
        public string TEMP_VSU { get; set; }
        public string TEMP_W9_W8 { get; set; }
        public string TEMP_INVOICE_NOTES { get; set; }
        public string TEMP_INVOICE_DESCRIPTION { get; set; }
        public string TEMP_BILLING_PRERIOD_DATE { get; set; }
        public string CONTACTS_CURRENT { get; set; }
        public string CONTACTS_PRIOR { get; set; }
    
        public virtual TB_APPROVER TB_APPROVER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_HIGHLIGHTS> TB_HIGHLIGHTS { get; set; }
        public virtual TB_HIGHLIGHTS TB_HIGHLIGHTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_HISTORIC_REMIT> TB_HISTORIC_REMIT { get; set; }
        public virtual TB_HISTORIC_REMIT TB_HISTORIC_REMIT1 { get; set; }
        public virtual TB_ORACLE_LEGAL_ENTITIES TB_ORACLE_LEGAL_ENTITIES { get; set; }
        public virtual TB_ORACLE_PAY_TERMS TB_ORACLE_PAY_TERMS { get; set; }
        public virtual TB_ORACLE_SOURCE TB_ORACLE_SOURCE { get; set; }
        public virtual TB_ORACLE_TYPE TB_ORACLE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALIAS> TB_ALIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMAIL_BACKUP> TB_EMAIL_BACKUP { get; set; }
        public string ALIAS_NAME { get; internal set; }
        public string EMAIL_BACKUP { get; internal set; }
    }
}
