//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VIEW_PERMISSIONS
    {
        public int VIEW_PERMISSION_ID { get; set; }
        public int FK_TB_LOGIN_ROLE_ID { get; set; }
        public string VIEW_NAME { get; set; }
        public bool CAN_VIEW { get; set; }
        public bool CAN_CREATE { get; set; }
        public bool CAN_EDIT { get; set; }
        public bool CAN_DELETE { get; set; }
    
        public virtual TB_LOGIN_ROLES TB_LOGIN_ROLES { get; set; }
    }
}
