//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WORKSPACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WORKSPACE()
        {
            this.WS_COMMENTS = new HashSet<WS_COMMENTS>();
            this.WS_LAST_ACTIONS = new HashSet<WS_LAST_ACTIONS>();
        }
    
        public int WS_ID { get; set; }
        public int TEMP_ID { get; set; }
        public Nullable<int> FK_WS_INVOICE_CATEGORY_ID { get; set; }
        public string WS_STATUS { get; set; }
        public string WS_REASON { get; set; }
        public string WS_EMAIL_RECEIVED { get; set; }
        public string WS_CREATED_DATE { get; set; }
        public string WS_SOURCE { get; set; }
        public string WS_HANDLED_BY { get; set; }
        public string WS_INVOICE_DATE { get; set; }
        public string WS_AMOUNT { get; set; }
        public string WS_INVOICE_NUMBER { get; set; }
        public Nullable<int> FK_WS_COMMENTS_ID { get; set; }
        public Nullable<int> FK_WS_LAST_ACTIONS_ID { get; set; }
        public int WS_ISDISABLED { get; set; }
        public string WS_TEMP_TAX_ID { get; set; }
        public string WS_TEMP_REMIT_TO { get; set; }
        public string WS_TEMP_SUPPLIER_NAME { get; set; }
        public string WS_TEMP_SUPPLIER_NUMBER { get; set; }
        public Nullable<int> WS_FK_TB_TEMPLATE_HISTORIC_REMIT_ID { get; set; }
        public string WS_TEMP_VENDOR_ACCOUNT { get; set; }
        public Nullable<int> WS_FK_TB_TEMPLATE_ALIAS_ID { get; set; }
        public string WS_TEMP_SUPPLIER_SITE { get; set; }
        public string WS_TEMP_ADDRESS { get; set; }
        public Nullable<int> WS_FK_TB_LEGAL_ENTITY_ID { get; set; }
        public string WS_TEMP_TAXPAYER_ID { get; set; }
        public Nullable<int> WS_FK_TB_ORACLE_TYPE_ID { get; set; }
        public string WS_TEMP_ORACLE_DESCRIPTION { get; set; }
        public Nullable<int> WS_FK_TB_ORACLE_PAY_TERMS_ID { get; set; }
        public string WS_TEMP_ACCOUNT_CODING { get; set; }
        public Nullable<int> WS_FK_TB_ORACLE_SOURCE_ID { get; set; }
        public string WS_TEMP_ORACLE_NOTES { get; set; }
        public string WS_TEMP_ORACLE_INSTRUCTIONS { get; set; }
        public Nullable<int> WS_FK_TB_HIGHLIGHTS_ID { get; set; }
        public Nullable<int> WS_FK_TB_EMAIL_BACKUP_ID { get; set; }
        public Nullable<int> WS_FK_TB_APPROVER_ID { get; set; }
        public string WS_TEMP_APPROVER_COMMENTS { get; set; }
        public string WS_TEMP_INVOICE_FORMAT { get; set; }
        public string WS_TEMP_INVOICE_TYPE { get; set; }
        public int WS_TEMP_ISDISABLED { get; set; }
        public string WS_TEMP_FOLDER { get; set; }
        public string WS_TEMP_PAYMENT_METHOD { get; set; }
        public string WS_TEMP_REMIT_TOACCOUNT { get; set; }
        public string WS_TEMP_BILLING_PERIOD { get; set; }
        public string WS_TEMP_DISTRIBUTION_COMBINATION { get; set; }
        public string WS_TEMP_ACCOUNTING_DATE { get; set; }
        public string WS_TEMP_VSU { get; set; }
        public string WS_TEMP_W9_W8 { get; set; }
        public string WS_TEMP_INVOICE_NOTES { get; set; }
        public string WS_TEMP_INVOICE_DESCRIPTION { get; set; }
        public string WS_TEMP_BILLING_PERIOD_DATE { get; set; }
        public string WS_CONTACTS_CURRENT { get; set; }
        public Nullable<int> WS_FK_TB_ORGANIZATION_TYPE_ID { get; set; }
    
        public virtual TB_APPROVER TB_APPROVER { get; set; }
        public virtual TB_HIGHLIGHTS TB_HIGHLIGHTS { get; set; }
        public virtual TB_HISTORIC_REMIT TB_HISTORIC_REMIT { get; set; }
        public virtual TB_ORACLE_LEGAL_ENTITIES TB_ORACLE_LEGAL_ENTITIES { get; set; }
        public virtual TB_ORACLE_PAY_TERMS TB_ORACLE_PAY_TERMS { get; set; }
        public virtual TB_ORACLE_SOURCE TB_ORACLE_SOURCE { get; set; }
        public virtual TB_ORACLE_TYPE TB_ORACLE_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_COMMENTS> WS_COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_LAST_ACTIONS> WS_LAST_ACTIONS { get; set; }
        public virtual WS_INVOICE_CATEGORY WS_INVOICE_CATEGORY { get; set; }
    }
}
