//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_INVOICE_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WS_INVOICE_CATEGORY()
        {
            this.TB_WORKSPACE = new HashSet<TB_WORKSPACE>();
        }
    
        public int INVOICE_CATEGORY_ID { get; set; }
        public string INVOICE_CATEGORY_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WORKSPACE> TB_WORKSPACE { get; set; }
    }
}
