//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsPayable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS_LAST_ACTIONS
    {
        public int LAST_ACTIONS_ID { get; set; }
        public Nullable<int> FK_WS_WORKSPACE_ID { get; set; }
        public System.DateTime LAST_ACTIONS_DATE { get; set; }
        public string LAST_ACTIONS_INFO { get; set; }
    
        public virtual TB_WORKSPACE TB_WORKSPACE { get; set; }
    }
}
